# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               'Core Skills'
tagline:             'Geoscientist to data scientist program'
description:         ''
url:                 http://core-skills.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jess Robertson
  url:               https://twitter.com/jesserobertson
  email:             jesse.robertson@csiro.au

gems:
    [jekyll-paginate]

# Custom vars
version:             1.0.0
